### ISSUE TITLE
STREAM support possible?

### ISSUE THREAD

**Issue by GaryOkie** [MisterWil/skybellpy#11]
I'm just loving the new HA 90.x stream component support for cameras.    In all your great work in reverse engineering the Skybell API, did you ever run across a way to get a live stream that would be compatible?    

Being able to detect front door motion and sending the stream to a Google hub in the back bedroom room would be so cool.     Of course the Skybell mobile app has the ability to live stream, but it's probably locked down, so my expectations are really low.  Just had to ask.

Thanks!

**Comment by nhorvath** [comment]
In all my poking around I didn't come across any ability to pick up or start a stream.

**Comment by thoukydides** [comment]
You can find details of how to start a live stream from a SkyBell HD at [Protocol-HTTPS](https://github.com/thoukydides/homebridge-skybell/wiki/Protocol-HTTPS#call-start). The video is provided H.264 encoded transported by SRTP as described at [Protocol-SRTP](https://github.com/thoukydides/homebridge-skybell/wiki/Protocol-SRTP).

It looks like Home Assistant's stream component supports H.264 (only) over RTP. It isn't obvious whether SRTP is supported, but it would always be possible to use FFmpeg to proxy the video stream. I do something similar in [homebridge-skybell](https://github.com/thoukydides/homebridge-skybell/blob/master/camera.js) to make the stream compatible with HomeKit.

**Comment by GaryOkie** [comment]
Thanks guys for the responses - especially the reverse-engineered protocol info.  Wow, great work on that detail @thoukydides !

I haven't yet found the documentation on how to implement the new HA stream support, other than looking at camera source that starts off statements such as  **homeassistant.components.camera import SUPPORT_STREAM**.     Apparently the HA streaming (and audio) hooks occur in the HA ffmpeg component code itself, if support_stream is enabled by the parent camera.

I'm not familiar with what is involved with using ffmpeg to proxy the Skybell video stream.  I'll take a closer look at your homebridge-skybell source to see how that's done.      But since Nick (who is a lot more familiar with Skybell) has already poked around the code, I doubt I'll find any straightforward way to implement it.

**Comment by tkdrob** [comment]
Sorry to bring up this old issue. I have revamped the HA integration to get the latest activity video playing. The streamer that HA uses does not support POST so no live calls. Still scratching my head on how to get push updates. I could not get enough info from @thoukydides work. He no longer has a working device so all can ask him is how he went about REing the API. I've been trying to MITM the mobile app with no success.
