### ISSUE TITLE
Could you please file a .tar.gz release?

### ISSUE THREAD

**Issue by onkelbeh** [MisterWil/skybellpy#13]
Hi Wil,

I would like to use your integration in my [Gentoo Overlay for Home Assistant](https://github.com/onkelbeh/HomeAssistantRepository). Therefor I need a release file in tar.gz format.
Home Assistant currently requires: `skybellpy==0.4.0`

This one exists at Pypi, but only in wheel format, cannot use this.

On Github you do not push releases.
Added this one today with the help of a fork: https://github.com/onkelbeh/HomeAssistantRepository/commit/6b34a071a18e75eeda69688d16bdcc4ffd1d1e18

A release on Github would be OK, but a Pypi tar.gz release **would be preferred**, because this could take use of Gentoo's mirror system.

Thanks
 \B.

**Comment by MisterWil** [comment]
I can do this no problem, however I'm not that familiar with python releases other than via bdist_wheel. Do you want a bdist in tar.gz format, or do you just want an sdist?

**Comment by onkelbeh** [comment]
sdist source distribution, please :-)
thanks for the hint, just added it to my [README](https://github.com/onkelbeh/HomeAssistantRepository#authors-welcome)

**Comment by onkelbeh** [comment]
Also it would be good if you add tags/releases on github. You can add tags for older releases: 

```sh
root@g18-hass:/tmp # git clone https://github.com/MisterWil/skybellpy.git
Klone nach 'skybellpy' ...
remote: Enumerating objects: 224, done.
remote: Total 224 (delta 0), reused 0 (delta 0), pack-reused 224
Empfange Objekte: 100% (224/224), 51.41 KiB | 378.00 KiB/s, Fertig.
Löse Unterschiede auf: 100% (129/129), Fertig.
root@g18-hass:/tmp # cd skybellpy/

root@g18-hass:/tmp/skybellpy # git tag
root@g18-hass:/tmp/skybellpy # git log --oneline
ac966d9 (HEAD -> master, origin/master, origin/HEAD) Update version to.0.4.0
a5d39f3 Ignore pycache and vscode
...
19bc8ca Merge pull request #7 from nhorvath/master
...
bda1396 Fixing lint errors
cac6af7 Added skybell.http containing testing requests.
6ada674 Initial commit
root@g18-hass:/tmp/skybellpy # git tag -a 0.2.0 19bc8ca -m "add prev release 0.2.0"
root@g18-hass:/tmp/skybellpy # git tag
0.2.0
root@g18-hass:/tmp/skybellpy #
```
Then you have to push the tag back to github:
```sh
git push origin 0.2.0
```
Github will automatically generate all the archives needed.

For adding a tag to the current HEAD, simply type
```sh
git tag {version number}
git push origin {version number}
```

**Comment by onkelbeh** [comment]
just saw, you did it perfectly on [abodepy](https://github.com/MisterWil/abodepy). But overall, I prefer source releases on Pypi.

This makes a `SRC_URI="mirror://pypi/${P:0:1}/${PN}/${P}.tar.gz"`, and uses Gentoo's mirror system.

For abodepy I took
`SRC_URI="https://github.com/MisterWil/${PN}/archive/v${PV}.tar.gz -> ${P}.tar.gz"`
this makes upgrading easy just as well.

See https://github.com/onkelbeh/HomeAssistantRepository/tree/master/dev-python/abodepy

While we're at it, I [updated](https://github.com/onkelbeh/HomeAssistantRepository/commit/06cf446c2add1f5bc5f32d6ff4202e21afba0806) it's metadata.xml.

**Comment by MisterWil** [comment]
Done!

https://pypi.org/project/skybellpy/0.5.0/#files

**Comment by onkelbeh** [comment]
0.5.0 compiles and works :-)
Could you do this for 0.4.0, too? And make the HA-Guys bump it to 0.5.0?

**Comment by MisterWil** [comment]
Tagged and uploaded sdist for 0.4.0 here: https://pypi.org/project/skybellpy/0.4.0/#files

**Comment by onkelbeh** [comment]
Perfect.
Updated: https://github.com/onkelbeh/HomeAssistantRepository/commit/53cdbe5f14186e6bdb5e2d0b38785f482d17d381
Thanks a lot, again.

**Comment by onkelbeh** [comment]
Just did a re-check, everythings still OK, just removed to abandonded fork.
