### ISSUE TITLE
Requirement is pinned: colorlog==3.0.1

### ISSUE THREAD

**Issue by MartinHjelmare** [MisterWil/skybellpy#16]
- This library supports an integration in Home Assistant.
- The upcoming pip resolver will be more strict in resolving package version conflicts:
http://pyfound.blogspot.com/2020/03/new-pip-resolver-to-roll-out-this-year.html#what-will-change
- To avoid future issues it would be good if this library would change its pinning to allow any higher version and just set a minimum version.

Thanks for your support of Home Assistant!

**Comment by MartinHjelmare** [comment]
@MisterWil Hi! did you see this issue? We would appreciate if this library can adjust the requirement pinning, release a new version and bump version used in home assistant. Thank you for your support!

**Comment by MisterWil** [comment]
Done in v0.6.3
